name: DATCREATIVE
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61696
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f5'
    - '#00fde0'
    - '#07bee6'
    - '#0c94ea'
    - '#5bf9e7'
  brandStrength: 0.5
  lightness: 0.6738480015192181
  saturation: 0.5
  rhythmicContrast: 0.8481155070476234
purpose: []
