name: DATCREATIVE
favicon: null
layout_spectrum: 0.5517745476681739
typography_spectrum: 0.702941759955138
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7322540818713605
  lightness: 0.6738480015192181
  saturation: 0.34432739834301174
  rhythmicContrast: 0.8481155070476234
purpose: []
